<?php

namespace AppBundle\Repository;

/**
 * CalificacionesFinalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionesFinalesRepository extends \Doctrine\ORM\EntityRepository
{
}
